# Generated by Django 4.1.7 on 2023-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todomanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
